### ISSUE TITLE
Testfiles: Path issue

### ISSUE THREAD

**Issue by LakshmiSwethaGavini** [arjunptm/GITS#26]
Error: Import is not being handled properly.
Changes are to be done in:
1.test_checkout.py
2.test_gits_add.py
3.test_gits_all_branch.py
4.test_gits_commit.py
5.test_gits_create_branch.py
6.test_gits_diff.py
7.test_gets_init.py
8.test_gets_remote_branch.py
9.test_gets_status.py
10.test_unstage.py.  
 @ramyasaimullapudi Can you please handle the 6-10 files, I will do the rest.

**Comment by LakshmiSwethaGavini** [comment]
First half of the files: PR raised https://github.com/arjunptm/GITS/pull/27

**Comment by ramyasaimullapudi** [comment]
The second half of the files: PR raised #28
