### ISSUE TITLE
Update documentation and readme.md

### ISSUE THREAD

**Issue by arjunptm** [arjunptm/GITS#34]
- [x] Add a detailed explanation to the readme.
- [x] Re-order the features listed in a sensible manner
- [ ] Add examples on how to run/use each feature

**Comment by arjunptm** [comment]
@LakshmiSwethaGavini can you update the `3. test` section in the readme.md's introduction section? Add a little more text about how test cases work.

**Comment by arjunptm** [comment]
This issue already has a pull request (#35) associated with it. You can use the [branch I created](tree/documentation_update_%2334) for it directly.

**Comment by arjunptm** [comment]
Reopening to update documentation further.

**Comment by rhnprabhune** [comment]
Working on - Re-order the features listed in a sensible manner
