### ISSUE TITLE
Check integrations.

### ISSUE THREAD

**Issue by arjunptm** [arjunptm/GITS#7]
Since we have forked this project, we may need to set up all the integrations once more: the Travis CI, Codecov, etc. Basically, run through all the badges on the readme and check if anything needs updating. Since @ramyasaimullapudi did this for the previous project, do you think you can take this over too?

**Comment by ramyasaimullapudi** [comment]
Yes, i can do that.

**Comment by ramyasaimullapudi** [comment]
Needs #29 and #31 .
But others are added by PR #30

**Comment by ramyasaimullapudi** [comment]
This is complete with all badges added to the project. Hence closing this issue.
