### ISSUE TITLE
Archive old and unused branches

### ISSUE THREAD

**Issue by arjunptm** [arjunptm/GITS#9]
There seem to be many old branches that the previous teams used, but I doubt they'll be functional anymore. As a housekeeping task, we can clean up those branches.

Deleting the branch itself would however remove valuable information, so we can try to archive it using the method listed in this thread:
https://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches

I'm assigning two people on this since there seem to be a lot of branches, even though it should be a quick task.

**Comment by LakshmiSwethaGavini** [comment]
@arjunptm Yes, makes sense. I went ahead and deleted the staled branches.
Thanks for pointing out this issue!
